/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package daw_tarea6;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Clase principal que contiene el JFrame principal.
 * 
 * @author Francisco Castillo Brull
 * @version 18/05/2022
 */
public class GestionMedicaVisual extends javax.swing.JFrame {

    //Atributos
    
    /**
     * Atributo de tipo GestionMedica que guardara el objeto dicho.
     */
    private GestionMedica gestion;

    //Constructores
    
    public GestionMedicaVisual() {
        gestion = new GestionMedica();
        try {
            gestion.cargarFicheros();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(GestionMedicaVisual.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextoInicio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabelEstPersonas = new javax.swing.JLabel();
        jLabelEstCentros = new javax.swing.JLabel();
        jLabelPaciente = new javax.swing.JLabel();
        jLabelPersonal = new javax.swing.JLabel();
        jLabelClinica = new javax.swing.JLabel();
        jLabelHospital = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEstPersonas = new javax.swing.JLabel();
        btnEstCentros = new javax.swing.JLabel();
        btnPacientes = new javax.swing.JLabel();
        btnPersonal = new javax.swing.JLabel();
        btnClinica = new javax.swing.JLabel();
        btnHospital = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanelTablas = new javax.swing.JTabbedPane();
        jPaneCentros = new javax.swing.JPanel();
        jPanePersonal = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnSalir.png"))); // NOI18N
        btnSalir.setText("jLabel12");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 10, 32, 32));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnMinimizar.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 10, 30, 30));

        jTextoInicio.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jTextoInicio.setForeground(new java.awt.Color(255, 255, 255));
        jTextoInicio.setText("Inicio");
        getContentPane().add(jTextoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 470, 60));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/20220514_174950_0000.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1080, 90));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Editado por Yaiza García");
        jLabel13.setToolTipText("");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 760, -1, -1));

        jLabelEstPersonas.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabelEstPersonas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstPersonas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstPersonas.setText("Estadísticas Personas");
        jLabelEstPersonas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEstPersonas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelEstPersonasMouseMoved(evt);
            }
        });
        jLabelEstPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEstPersonasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelEstPersonasMouseExited(evt);
            }
        });
        jPanel1.add(jLabelEstPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 310, 50));

        jLabelEstCentros.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabelEstCentros.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstCentros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstCentros.setText("Estadísticas Centros");
        jLabelEstCentros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelEstCentros.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelEstCentrosMouseMoved(evt);
            }
        });
        jLabelEstCentros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEstCentrosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelEstCentrosMouseExited(evt);
            }
        });
        jPanel1.add(jLabelEstCentros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 310, 50));

        jLabelPaciente.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabelPaciente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPaciente.setText("Gestión Pacientes");
        jLabelPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPaciente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelPacienteMouseMoved(evt);
            }
        });
        jLabelPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPacienteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPacienteMouseExited(evt);
            }
        });
        jPanel1.add(jLabelPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 310, 50));

        jLabelPersonal.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabelPersonal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPersonal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPersonal.setText("Gestión Personal");
        jLabelPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPersonal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelPersonalMouseMoved(evt);
            }
        });
        jLabelPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPersonalMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPersonalMouseExited(evt);
            }
        });
        jPanel1.add(jLabelPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 310, 50));

        jLabelClinica.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabelClinica.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClinica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClinica.setText("Gestión Clínica");
        jLabelClinica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClinica.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelClinicaMouseMoved(evt);
            }
        });
        jLabelClinica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClinicaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelClinicaMouseExited(evt);
            }
        });
        jPanel1.add(jLabelClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 310, 50));

        jLabelHospital.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabelHospital.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHospital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHospital.setText("Gestión Hospital");
        jLabelHospital.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelHospital.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelHospitalMouseMoved(evt);
            }
        });
        jLabelHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHospitalMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHospitalMouseExited(evt);
            }
        });
        jPanel1.add(jLabelHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 310, 50));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/computadora (1).png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 30, 30));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/historial-medico (1).png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 30, 30));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/paciente (1).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 30, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/equipo-medico.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 30, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/kit-de-primeros-auxilios.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 30, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 190, 190));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gestión Médica");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 350, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/20220514_182056_0000.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 250));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hospital.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 30, 30));

        btnEstPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPrincipal.png"))); // NOI18N
        jPanel1.add(btnEstPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 308, 50));

        btnEstCentros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPrincipal.png"))); // NOI18N
        jPanel1.add(btnEstCentros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 308, 50));

        btnPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPrincipal.png"))); // NOI18N
        jPanel1.add(btnPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 308, 50));

        btnPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPrincipal.png"))); // NOI18N
        jPanel1.add(btnPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 308, 50));

        btnClinica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPrincipal.png"))); // NOI18N
        jPanel1.add(btnClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 308, 50));

        btnHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPrincipal.png"))); // NOI18N
        jPanel1.add(btnHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 308, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/20220514_1845131.gif"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 246, 350, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 790));

        javax.swing.GroupLayout jPaneCentrosLayout = new javax.swing.GroupLayout(jPaneCentros);
        jPaneCentros.setLayout(jPaneCentrosLayout);
        jPaneCentrosLayout.setHorizontalGroup(
            jPaneCentrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPaneCentrosLayout.setVerticalGroup(
            jPaneCentrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );

        jPanelTablas.addTab("Centros", jPaneCentros);

        javax.swing.GroupLayout jPanePersonalLayout = new javax.swing.GroupLayout(jPanePersonal);
        jPanePersonal.setLayout(jPanePersonalLayout);
        jPanePersonalLayout.setHorizontalGroup(
            jPanePersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanePersonalLayout.setVerticalGroup(
            jPanePersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );

        jPanelTablas.addTab("Personas", jPanePersonal);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );

        jPanelTablas.addTab("Info", jPanel4);

        getContentPane().add(jPanelTablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 1080, 730));
        jPanelTablas.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //Funciones
    
    /**
     * Funcion que se encarga que cuando el puntero salga del lugar del jLabel
     * aplique una imagen.
     *
     * @param evt
     */
    private void jLabelHospitalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHospitalMouseExited
        btnHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPrincipal.png")));
    }//GEN-LAST:event_jLabelHospitalMouseExited

    /**
     * Funcion asignada al label de Hospital, al ser pulsado mostrara el panel de GestionCentro en el TabbedPanel.
     *
     * @param evt
     */
    private void jLabelHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHospitalMouseClicked
        jTextoInicio.setText("Gestión Hospital");
        GestionMedicaCentro hosp = new GestionMedicaCentro(gestion, 0);
        jPanelTablas.setComponentAt(0, hosp);
        jPanelTablas.setSelectedIndex(0);
        this.revalidate();
    }//GEN-LAST:event_jLabelHospitalMouseClicked

    /**
     * Funcion que se encarga que cuando el puntero este dentro del lugar del
     * jLabel aplique una imagen.
     *
     * @param evt
     */
    private void jLabelHospitalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHospitalMouseMoved
        btnHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPulsado.png")));
    }//GEN-LAST:event_jLabelHospitalMouseMoved

    /**
     * Funcion que se encarga que cuando el puntero salga del lugar del jLabel
     * aplique una imagen.
     *
     * @param evt
     */
    private void jLabelClinicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClinicaMouseExited
        btnClinica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPrincipal.png")));
    }//GEN-LAST:event_jLabelClinicaMouseExited

    /**
     * Funcion asignada al label de Clinica, al ser pulsado mostrara el panel de GestionCentros en el TabbedPanel.
     *
     * @param evt
     */
    private void jLabelClinicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClinicaMouseClicked
        jTextoInicio.setText("Gestión Clínica");
        GestionMedicaCentro hosp = new GestionMedicaCentro(gestion, 1);
        jPanelTablas.setComponentAt(0, hosp);
        jPanelTablas.setSelectedIndex(0);
        this.revalidate();
    }//GEN-LAST:event_jLabelClinicaMouseClicked

    /**
     * Funcion que se encarga que cuando el puntero este dentro del lugar del
     * jLabel aplique una imagen.
     *
     * @param evt
     */
    private void jLabelClinicaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClinicaMouseMoved
        btnClinica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPulsado.png")));
    }//GEN-LAST:event_jLabelClinicaMouseMoved

    /**
     * Funcion que se encarga que cuando el puntero salga del lugar del jLabel
     * aplique una imagen.
     *
     * @param evt
     */
    private void jLabelPersonalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPersonalMouseExited
        btnPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPrincipal.png")));
    }//GEN-LAST:event_jLabelPersonalMouseExited

    /**
     * Funcion asignada al label de Personal, al ser pulsado mostrara el panel de GestionPersona en el TabbedPanel.
     *
     * @param evt
     */
    private void jLabelPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPersonalMouseClicked
        jTextoInicio.setText("Gestión Personal");
        GestionPersona pers = new GestionPersona(gestion, 1);
        jPanelTablas.setComponentAt(1, pers);
        jPanelTablas.setSelectedIndex(1);
        this.revalidate();
    }//GEN-LAST:event_jLabelPersonalMouseClicked

    /**
     * Funcion que se encarga que cuando el puntero este dentro del lugar del
     * jLabel aplique una imagen.
     *
     * @param evt
     */
    private void jLabelPersonalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPersonalMouseMoved
        btnPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPulsado.png")));
    }//GEN-LAST:event_jLabelPersonalMouseMoved

    /**
     * Funcion que se encarga que cuando el puntero salga del lugar del jLabel
     * aplique una imagen.
     *
     * @param evt
     */
    private void jLabelPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPacienteMouseExited
        btnPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPrincipal.png")));
    }//GEN-LAST:event_jLabelPacienteMouseExited

    /**
     * Funcion asignada al label de Pacientes, al ser pulsado mostrara el panel de GestionPersona en el TabbedPanel.
     *
     * @param evt
     */
    private void jLabelPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPacienteMouseClicked
        jTextoInicio.setText("Gestión Pacientes");
        GestionPersona pers = new GestionPersona(gestion, 2);
        jPanelTablas.setComponentAt(1, pers);
        jPanelTablas.setSelectedIndex(1);
        this.revalidate();
    }//GEN-LAST:event_jLabelPacienteMouseClicked

    /**
     * Funcion que se encarga que cuando el puntero este dentro del lugar del
     * jLabel aplique una imagen.
     *
     * @param evt
     */
    private void jLabelPacienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPacienteMouseMoved
        btnPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPulsado.png")));
    }//GEN-LAST:event_jLabelPacienteMouseMoved

    /**
     * Funcion que se encarga que cuando el puntero salga del lugar del jLabel
     * aplique una imagen.
     *
     * @param evt
     */
    private void jLabelEstCentrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEstCentrosMouseExited
        btnEstCentros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPrincipal.png")));
    }//GEN-LAST:event_jLabelEstCentrosMouseExited

    /**
     * Funcion asignada al label de EstCentros, al ser pulsado mostrara el panel de GestionEstadisticas en el TabbedPanel.
     *
     * @param evt
     */
    private void jLabelEstCentrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEstCentrosMouseClicked
        jTextoInicio.setText("Estadísticas Centros");
        GestionEstadisticas est = new GestionEstadisticas(gestion, 0);
        jPanelTablas.setComponentAt(2, est);
        jPanelTablas.setSelectedIndex(2);
        this.revalidate();
    }//GEN-LAST:event_jLabelEstCentrosMouseClicked

    /**
     * Funcion que se encarga que cuando el puntero este dentro del lugar del
     * jLabel aplique una imagen.
     *
     * @param evt
     */
    private void jLabelEstCentrosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEstCentrosMouseMoved
        btnEstCentros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPulsado.png")));
    }//GEN-LAST:event_jLabelEstCentrosMouseMoved

    /**
     * Funcion asignada al label de EstPersonas, al ser pulsado mostrara el panel de GestionEstadisticas en el TabbedPanel.
     *
     * @param evt
     */
    private void jLabelEstPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEstPersonasMouseClicked
        jTextoInicio.setText("Estadísticas Personas");
        GestionEstadisticas est = new GestionEstadisticas(gestion, 1);
        jPanelTablas.setComponentAt(2, est);
        jPanelTablas.setSelectedIndex(2);
        this.revalidate();
    }//GEN-LAST:event_jLabelEstPersonasMouseClicked

    /**
     * Funcion asignada al label de cerrar, cuando se pulse el label, el programa finalizará y guarda el estado del programa en ficheros.
     *
     * @param evt
     */
    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        try {
            gestion.pasarFichero(gestion);
        } catch (IOException ex) {
            Logger.getLogger(GestionMedicaVisual.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Se guardo el estado actual del programa");
        System.exit(0);

    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * Funcion asignada al label de minimizar, cuando se pulse el label, el JFrame se minimizara
     *
     * @param evt
     */
    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        this.setExtendedState(1);
    }//GEN-LAST:event_jLabel12MousePressed

    /**
     * Funcion que se encarga que cuando el puntero salga del lugar del jLabel
     * aplique una imagen.
     *
     * @param evt
     */
    private void jLabelEstPersonasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEstPersonasMouseExited
        btnEstPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPrincipal.png")));
    }//GEN-LAST:event_jLabelEstPersonasMouseExited

    /**
     * Funcion que se encarga que cuando el puntero este dentro del lugar del jLabel
     * aplique una imagen.
     *
     * @param evt
     */
    private void jLabelEstPersonasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEstPersonasMouseMoved
        btnEstPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botonPulsado.png")));
    }//GEN-LAST:event_jLabelEstPersonasMouseMoved

    /**
     * Funcion encargada de asignar un icono al programa.
     *
     * @param evt
     */
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes\\icono.png"));

        return retValue;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionMedicaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionMedicaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionMedicaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionMedicaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionMedicaVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClinica;
    private javax.swing.JLabel btnEstCentros;
    private javax.swing.JLabel btnEstPersonas;
    private javax.swing.JLabel btnHospital;
    private javax.swing.JLabel btnPacientes;
    private javax.swing.JLabel btnPersonal;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClinica;
    private javax.swing.JLabel jLabelEstCentros;
    private javax.swing.JLabel jLabelEstPersonas;
    private javax.swing.JLabel jLabelHospital;
    private javax.swing.JLabel jLabelPaciente;
    private javax.swing.JLabel jLabelPersonal;
    private javax.swing.JPanel jPaneCentros;
    private javax.swing.JPanel jPanePersonal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jPanelTablas;
    private javax.swing.JLabel jTextoInicio;
    // End of variables declaration//GEN-END:variables
}
